/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as ProtectedOverviewIndexImport } from './routes/_protected/overview/index'
import { Route as ProtectedHomeIndexImport } from './routes/_protected/home/index'
import { Route as ProtectedCompareIndexImport } from './routes/_protected/compare/index'
import { Route as ProtectedOverviewOverviewIndexImport } from './routes/_protected/overview/$overview/index'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedOverviewIndexRoute = ProtectedOverviewIndexImport.update({
  path: '/overview/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedHomeIndexRoute = ProtectedHomeIndexImport.update({
  path: '/home/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedCompareIndexRoute = ProtectedCompareIndexImport.update({
  path: '/compare/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedOverviewOverviewIndexRoute =
  ProtectedOverviewOverviewIndexImport.update({
    path: '/overview/$overview/',
    getParentRoute: () => ProtectedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/compare/': {
      id: '/_protected/compare/'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof ProtectedCompareIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/home/': {
      id: '/_protected/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/overview/': {
      id: '/_protected/overview/'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof ProtectedOverviewIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/overview/$overview/': {
      id: '/_protected/overview/$overview/'
      path: '/overview/$overview'
      fullPath: '/overview/$overview'
      preLoaderRoute: typeof ProtectedOverviewOverviewIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ProtectedRoute: ProtectedRoute.addChildren({
    ProtectedCompareIndexRoute,
    ProtectedHomeIndexRoute,
    ProtectedOverviewIndexRoute,
    ProtectedOverviewOverviewIndexRoute,
  }),
  LoginIndexRoute,
})

/* prettier-ignore-end */
